#!/bin/bash -e

TARGET=$1
OUTPUT=${2:-$TARGET}

if [ "x${TARGET}" == "x" ]; then
	echo "Usage: `basename $0` target [output]"
	exit 1
fi

if [ ! -e ".godeps" ]; then
	echo "Missing .godeps! Run bootstrap.sh first!"
	exit 1
fi

if [ ! -e ".godeps/src/github.com/gophergala/gopher_talkie/app" ]; then
	mkdir -p ".godeps/src/github.com/gophergala/gopher_talkie"
	cd ".godeps/src/github.com/gophergala/gopher_talkie" && ln -s ../../../../../src/cli/app app && cd -
fi

if [ ! -e ".godeps/src/github.com/gophergala/gopher_talkie/common" ]; then
	mkdir -p ".godeps/src/github.com/gophergala/gopher_talkie"
	cd ".godeps/src/github.com/gophergala/gopher_talkie" && ln -s ../../../../../src/common common && cd -
fi

if [ ! -e ".godeps/src/github.com/gophergala/gopher_talkie/audio" ]; then
	mkdir -p ".godeps/src/github.com/gophergala/gopher_talkie"
	cd ".godeps/src/github.com/gophergala/gopher_talkie" && ln -s ../../../../../src/audio audio && cd -
fi

if [ ! -e ".godeps/src/github.com/gophergala/gopher_talkie/crypto" ]; then
	mkdir -p ".godeps/src/github.com/gophergala/gopher_talkie"
	cd ".godeps/src/github.com/gophergala/gopher_talkie" && ln -s ../../../../../src/crypto crypto && cd -
fi

PACKAGE=./src/$TARGET
OUTPUT=./bin/$OUTPUT

source gvp in
go build -o $OUTPUT $PACKAGE
source gvp out

