#!/bin/bash -e

TARGET=$1
OUTPUT=${2:-$TARGET}

if [ "x${TARGET}" == "x" ]; then
	echo "Usage: `basename $0` target [output]"
	exit 1
fi

if [ ! -e ".godeps" ]; then
	echo "Missing .godeps! Run bootstrap.sh first!"
	exit 1
fi

if [ ! -e ".godeps/src/github.com/gophergala/gopher_talkie/src" ]; then
	mkdir -p ".godeps/src/github.com/gophergala/gopher_talkie"
	cd ".godeps/src/github.com/gophergala/gopher_talkie" && ln -s ../../../../../src src && cd -
fi

PACKAGE=./src/$TARGET
OUTPUT=./bin/$OUTPUT

source gvp in
go build -o $OUTPUT $PACKAGE
source gvp out

