#!/bin/bash -e

OPTIND=1
while getopts "h?vf:" opt; do
    case "$opt" in
    v)  VERBOSE=-v
        ;;
    esac
done

shift $((OPTIND-1))

TARGET=$1
if [ "x${TARGET}" == "x" ]; then
	echo "Usage: `basename $0` target"
	exit 1
fi
shift

PACKAGE=./src/$TARGET
OUTPUT=./bin/$TARGET

if [ ! -e ".godeps" ]; then
	echo "Missing .godeps! Run bootstrap.sh first!"
	exit 1
fi

source gvp in
go test $VERBOSE -o $OUTPUT $PACKAGE $@
source gvp out

